CFLAGS = -g -Wall -W -fPIC -DNOHEAPALLOC -DMORE_NOHEAPALLOC -DDELAY_DEBUG_STAT ${OSCFLAGS}
CPPFLAGS =
STRIP = $(ECHO)
CC = $(PURIFY) gcc
CPLUSPLUS = $(PURIFY) g++
ifndef AVERTEC_LICENSE
AVERTEC_LICENSE = NO_LICENSE
endif

