.TH XTAS 1 "06 November 2001" "AVERTEC" "AVERTEC CAD Tools"

.SH NAME
.PP
\fBxtas\fP \- graphical timing viewer

.so man1/avt_origin.1

.SH SYNOPSIS
.PP
xtas

.SH DESCRIPTION
.PP
\fBxtas\fP is a graphical timing viewer who allow to visualise 
a 'perfmodule' file, either detailled or general.

.SH THE X RESSOURCES FILE
.PP
The file AvtTools/etc/Xtas allow to set the parameters of the graphical interface.
The color and the size of the windows of \fBxtas\fP can be modified in this file.

.SH OPTIONS
.PP
xtas has neither arguments nor options.

.SH SEE ALSO
        tas(1), ttx(5), dtx(5)

.so man1/avt_bug_report.1

