.TH XYAGLE 1 "06 November 2001" "AVERTEC" "AVERTEC CAD Tools"

.SH NAME
.PP
\fBxyagle\fP \- graphical circuit viewer

.so man1/avt_origin.1

.SH SYNOPSIS
.PP
xyagle

.SH DESCRIPTION
.PP
\fBxyagle\fP is a graphical viewer which allows browsing of
disassembled gate netlists (CNS files) and structural netlists (SPICE, Verilog, VHDL).

.SH OPTIONS
.PP
xyagle has neither arguments nor options.

.SH SEE ALSO
        yagle(1)

.so man1/avt_bug_report.1

