#!/bin/sh -f


SSTRIP="/usr/local/bin/strip"
SRSH="/usr/ucb/rsh"

LSTRIP="/usr/bin/strip"
LRSH="/usr/bin/rsh"

PATH="/users/disk02/avertec/Release/AvtTools_2.3p6_040421/tools"
#PATH="/users/disk02/avertec/distrib_ref/tools"
SOLARIS="Solaris_2.6 Solaris_2.7 Solaris_2.8 Solaris_2.8_64 Solaris_2.9 Solaris_2.9_64"
LINUX="Linux_2.2 Linux_2.4"

hostlog()
{
  if   [ "$1" = "Solaris_2.5" ] ; then
    echo "brisbane"
  elif [ "$1" = "Solaris_2.6" ] ; then
    echo "londres"
  elif [ "$1" = "Solaris_2.7" ] ; then
    echo "londres"
  elif [ "$1" = "Solaris_2.8" ] ; then
    echo "paris"
  elif [ "$1" = "Solaris_2.8_64" ] ; then
    echo "paris"
  elif [ "$1" = "Solaris_2.9" ] ; then
    echo "denver"
  elif [ "$1" = "Solaris_2.9_64" ] ; then
    echo "denver"
  elif [ "$1" = "Linux_2.2" ] ; then
    echo "univers"
  elif [ "$1" = "Linux_2.4" ] ; then
    echo "oslo"
  elif [ "$1" = "Linux_2.4_mdk" ] ; then
    echo "rio"
  elif [ "$1" = "Linux_demo" ] ; then
    echo "demo"
  fi
}

loop()
{
  Rsh=$1
  Strip=$2
  Bin=$3
  List=$4
  
  for os in $List ; do
    host=`hostlog $os`
    echo "======== $host"
    $Rsh $host "cd $PATH/$os/bin ; $Strip $Bin"
    echo "$host : $PATH/$os/bin : $Strip $Bin"
  done
}

loop $SRSH $SSTRIP gnstest "$SOLARIS"
loop $LRSH $LSTRIP gnstest "$LINUX"
