
// File generated by avtwig wrapper generator

#include <stdio.h>
#include <stdlib.h>
#include <setjmp.h>
#include <strings.h>
#include <signal.h>
extern void avt_PushSegVExit (void (*fexit)(int), int code);
extern void avt_PopSegVExit ();
extern void avt_PushFPEExit (void (*fexit)(int), int code);
extern void avt_PopFPEExit ();
extern void avt_PushKillExit (void (*fexit)(int), int code);
extern void avt_PopKillExit ();
extern void avt_PushSegVMessage (char *message);
extern void avt_PopSegVMessage ();
extern void avt_PushFPEMessage (char *message);
extern void avt_PopFPEMessage ();
extern void avt_PushKillMessage (char *message);
extern void avt_PopKillMessage ();
#define T_POINTER    0x1   /* pointer  */
#define T_INT        0x2   /* int      */
#define T_LONG       0x3   /* long     */
#define T_CHAR       0x4   /* char     */
#define T_DOUBLE     0x5   /* double   */
#define T_VOID       0x6   /* no type  */
typedef struct t_arg {                       
    char *NAME;
    char *TYPE;
    void *VALUE;
    int   POINTER; /* pointer level, 0 1 2 3 ... */
} t_arg;
extern t_arg *NewArg ();
extern int TypeCheck (t_arg *arg, char *type);
extern int GetPointer (t_arg *arg);
extern void SetPointer (t_arg *arg, int p);
extern void SetType (t_arg *arg, char *t);
static jmp_buf env;

static void Exit (int val)
{
    longjmp (env, val);
}
#define AVTWIG_AVOID_CONFLICT
// Original include file
#include "/dsk/l1/tasyag/tasyag/distrib/share/../docxml2/../sources/api/tma/tma_API.h"

// Others
