.TH XCONES 1 "06 November 2001" "AVERTEC" "AVERTEC CAD Tools"

.SH NAME
.PP
\fBxcones\fP \- graphical cone viewer

.so man1/avt_origin.1

.SH SYNOPSIS
.PP
xcones

.SH DESCRIPTION
.PP
\fBxcones\fP is a graphical cone viewer who allow to visualise a
disassembled gate netlist.

.SH OPTIONS
.PP
xcones has neither arguments nor options.

.SH SEE ALSO
        hitas(1), tas(1)

.so man1/avt_bug_report.1

