.TH XYAGLE 1 "06 November 2001" "AVERTEC" "AVERTEC CAD Tools"

.SH NAME
.PP
\fBxyagle\fP \- graphical circuit viewer

.so man1/avt_origin.1

.SH SYNOPSIS
.PP
xyagle

.SH DESCRIPTION
.PP
\fBxyagle\fP is a graphical circuit viewer who allow to visualise a
disassembled gate netlist.

.SH OPTIONS
.PP
xyagle has neither arguments nor options.

.SH SEE ALSO
        yagle(1)

.so man1/avt_bug_report.1

