/* XPM */
static char *LogoAsim[] = {
/* width height num_colors chars_per_pixel */
"    96    75       33            1",
/* colors */
". c #565b38",
"# c #817654",
"a c #987130",
"b c #958569",
"c c #ad7c32",
"d c #ba8533",
"e c #b28d58",
"f c #b4b0a2",
"g c #cb852f",
"h c #ca923f",
"i c #ca9446",
"j c #c99c64",
"k c #c6baa1",
"l c #c6c6c6",
"m c #cecec6",
"n c None",
"o c #d68429",
"p c #db862e",
"q c #e19431",
"r c #eb9435",
"s c #e0983b",
"t c #d6a04a",
"u c #eb9c39",
"v c #eba344",
"w c #d79e55",
"x c #e6a758",
"y c #e4b261",
"z c #f7c05c",
"A c #e2b87e",
"B c #fbcc7b",
"C c #d7c9b6",
"D c #e2e2da",
"E c #000000",
/* pixels */
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnnCnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCnmAfmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCnnAfjtbknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmCnCCkvadywwlmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCCmwbduihwihbknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCnAebvehuirihxiwlnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmCnCjjseduiqthuhstihbknnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnCkfxccuwhuhrhhsdrhgyijmmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnmCnAd#uthueshduhqvhuestihbCnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmCnCjbvheripvhrtsqdrdgsduhhzdAnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCnCAfxgarwhvhuhhphphguhqhdudsihdbknnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmnnClAgauvtuihshpigshrdgsdqdguduhhvcAnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCnkt#sviripshrtprdpdcpcghgudugdudqthhjCnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnCnCwbtqerhhuhrshrhpgcpdcscvdggdqdgsguhpvdAnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnCnnAfjpapthuhsqhrhgsgrhduchdadcghguduggqcqthhfCnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnmnnCCAsasvtuhhpdqhguhpscqadgawd..aucggdqhgsduhghcAnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnCnCtbtvjuiduirvhuhhpcqdcscxtaaaaaatcptgudqddqdpxgifCnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnCnnAbircpthvwuvhrhhpdrhdudttacaaaaaaa.cscgodqdgududghaAnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnmnnAfjrasvtrthuirhgutrvcrcdhaiiaaaawzBwa.dzdopducqgcqdqxdilCnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnmnnCmks#hvxuthriphhuhsvdrhchctwaaaaeyBByzBwaaacqdgggqdgqcudggcAnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnCnCxbwvjshhuhrvhrthscrhcsdwyaaaaaeyBBxa.azBwa.dzdqgdqcqgcqdgxdwlmnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnCnmAfjrbswtuxsvirddpdrtcuihtaceaaaizBBwc....cBBjaaaapcgpcqggqcrdgc#Annnnnnnnnnnnnnnnnnn",
"nnnnnnmnnCCAs#hxyvwtrephhutsvdrhchaiwaaaajzBBycdda....iBBea.dzdqgdqaogcqdgwcwnnnnnnnnnnnnnnnnnnn",
"nnnnnnCnCxbwvwutisirshutsrcrdcsdwyaaaaaizBBxechih....eciBBcaaaapdgudqdgqcpdddbknnnnnnnnnnnnnnnnn",
"nnnCnmAbwveswtvxvvtrhdpdrhcuhtxaacaacjBBBxcciiecjiaadixaxBzaa.ivcpgcpagpcudhwaynnnnnnnnnnnnnnnnn",
"nnnCfjhavxyvwtriuhhutuvdrhcsaewaa#cwBBBxcciiecejjichwjjiayBzaaadcphgucrgdpapicgbCnnnnnnnnnnnnnnn",
"nmfjbxxwvxwviuthvtsvdrhcseiyaaaaeyBBzicdieceejjjbffjjijjiayByaa.dvcggcpcgpcuddvaAnnnnnnnnnnnnnnn",
"f#exeyxtvwvxwvwhuhrhcshwzaaaaaeyBByeadieaejjjjfbfffffjiejdayByaaahcpggrcqddpagtdhfCmnnnnnnnnnnnn",
"b#eAexyxvivihvhuxvvwwxaceaaaeyBByeadieaejjjjfffbbbfffjjijjdazztaa.dvaogcqdgqcuddhaAnnnnnnnnnnnnn",
"fb##ewevwwxxvxwvipvhxyaaaaeyBBydadieaejjjjffffbbbfffffjeiejcavzwaadwcrgducqgcpcgwchfmnnnnnnnnnnn",
"fb##jAdxxvviuisvwuytdaaaiyBByaatieaejjjjflfb#bfffffffffjiijjcczziaaacqaggcqdducpccgajnnnnnnnnnnn",
"nfbb##etwvwvvyvxhuirdcceBBze..aiaejjjfflfbbbffffffbfffffjiiejaiBzia.izcqgdqaggaqcdvaiCnnnnnnnnnn",
"nnbb#aAxevishhvwvxxuxicazBya.a.awdjkfffffbffffbbfffffffffjdijjaiBBdaaaapdgucqgcuasgagbAmnnnnnnnn",
"nnnbb#ccewxvxxxwvwhuirdddABAa##adjfffbbblmffbbbfflffffllffjijjiaiBzda.dzdpgcradgcrddvailnnnnnnnn",
"nnnmbb#aAwivevthvwvvwuwhacBByejxAflbbfffbffbfffffflffflffffjhjjiaiBzaaaaapdcucsgcradhagbkCnnnnnn",
"nnnnlbbaeeexxxxwviuhduwuaejBBAAyAAfffffbbbflfflDlffflfbbfbffjijjiawBza..cvcggapccqaqgdvadCnnnnnn",
"nnnnnfbb##yihvevwtvxvvhredcjBBAyyAkffbbbfffllmDDDfffffbbfffffjidhhawzza.adcpgdrchgaqcdvagbCmnnnn",
"nnnnnnfb##AihzwvwsvdrthvwvaeABByyyAfffbffffflfmffffbflffffbbffdtca.azzva..cuadgapdcudsgasadmnnnn",
"nnnnnnnbbbaawitvivxwvwsudradeABAyyyAffffffffffffffbbffffbb#blfjca...dzzwa.ducgqcuadgaodcvedfnmnn",
"nnnnnnnlbb#eBihvivipuhuthvwhaeBBAyywAfffffffffffbffffffb#bllfjyta.acyBBzc.gaapccoaggcucdgagaeCnn",
"nnnnnnnnlbb#aatitvwvxiuipseradeABAwwyjfffffbbbflffffb#bfllfkAAAyweyBBwddaagaaqdgqaqccgaggavdajnn",
"nnnnnnnnnlbbaeBhhthuhpuhuthvjhaeBBAwwyjffbbbbbblmfb##ffffkAAAwjyzBByhaagaarcdoagcapcgqaqccqaaabm",
"nnnnnnnnnnfbb#eahxvvwuvhudpseradjBBywwyfffbbbffflb#bllfkAAAwjwBBBxdagaaqacoagoarcdoagcaoadpcvi.b",
"nnnnnnnnnnnbb#aeyeshhuiqvtuvhredajBBywwAbffffffbbmllfkAAAwjwyBByedaaoaaqdhqaqcagaggaqcdqagaaha.#",
"nnnnnnnnnnnmbb#bwevwtviqhdqhpvwuaeABBywwjfffbbbfflfkAAAwjxzBBAtc.gaarddoagcapcgqaqcagacgazi..a##",
"nnnnnnnnnnnnlbb#aeteshhuwvuisscqadeABAwwwffffffffkAAAjwwzBByhadcapaaoagocqcdpagcaoccqavh.aaaa..#",
"nnnnnnnnnnnnnfb#awycvthucqsduisvwhaeBBAwwyjffffkAAAjjwyBByedaagaaqddpaocaoacgaqccqaddadcaa....bf",
"nnnnnnnnnnnnnnf#baacsdshiuthudrhdpadbBByyyyjkyzAAwwxzBBAhcaoaaqcdpagcapagqasgaoacgavha.a....blnn",
"nnnnnnnnnnnnnnnf##awzcvdhrcphdvthved#eBBywiitxzywwzBBxaagaaraaoaggaqcdqagcaoacqcvt.aaa....blnnnn",
"nnnnnnnnnnnnnnnnb##aeathvviuhdrcphhpadwBBe..aajyzBBwedaaoaarcdqaqcaoacgaqcduadgaccaa#...blnnnnnn",
"nnnnnnnnnnnnnnnnlb##ajxcuddrtsvhuhhuadajBB#.aezBBAha.gaaucdoagcapcgqapcapacgavva.aa...blnnnnnnnn",
"nnnnnnnnnnnnnnnnnf###ewevhtuhuddrdpxihaczBziyBBxeagaapaaoaggarcdoagcaoaaqcvh.aaaa...#lnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnf###aehauhhvivuirdcpacayBBzwcdaaoaarchpapcaoaggaqgdqadgadcaaa...#fnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnf##ayxevdhsarhduhhved.exxhaapaaucdoagcarcdpaqcaqacgavta.aa...#fnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnb###aeheutivihuapdcg.da.haaqacoapgcrchpagcapacqdvtaaaaa...blnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnmb##aAxcvcdrapiduhhuag.apacrchparacoaggaqgduagdaccaaa...bfnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnlb##eeaxivvduddpaphcp.crchgapccpchscqccpacgavwa.aa...bfnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnf###awhauddvdvsdudcpacgargcuchgaoccpadscvh.aaaa...#fnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnf###widvhhsarccrchucsgdracoapgcuddqahdahcaa....#fnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnb##a#ihavdhvhhrapcapcdpcsoaracpacgczwa.aa...#fnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnmb##aAwdvdhpapgcuddrcpgapccsagsavi.aaa....#fnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnlb###aatevsdvddpaggapddvchpahcaiaaa#...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnlb##aAtaucdsahscvgcpadhaddczi..a#...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnf###jeevetuascapahsahtdza.aaa#...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnb##.#ihavddvdiuahdahaaxa###...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnb###AwevcdhatdahdiBc.a##...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnlb####cwaiwaxhctaaea##...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnlb##aAiaziataey####...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnf###eceAeyB#####...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnf#######ee###...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnf#.#######...#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnmb.........#fnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnl....E...flnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn",
"nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnlfbb##fmnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn"
};
